name: Github pages deploy

on:
  push:
    branches: [ "master", "build-flow" ]
    
permissions:
  contents: read
  pages: write
  id-token: write
    
jobs:
  deploy: 
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
      
    runs-on: ubuntu-latest
    
    env: 
      CI: false
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy React to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: bitovi/github-actions-react-to-ghp@1782b3410beca05fb72bd089e5620790c0c4d883
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        # Specifies the path of the static assets after building
        path: build
